server:
  port: ${port:8082}

spring:
  application:
    name: eshop-price-service

  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://192.168.1.2:3306/eshop?characterEncoding=utf-8&useSSL=false
    type: com.alibaba.druid.pool.DruidDataSource

  jackson:
    default-property-inclusion: non_null

  redis:
    # 连接redis主集群twemproxy
    host: 192.168.1.10
    port: 1111
#    password: 123456
    timeout: 6000     # 连接超时时间（毫秒）
    pool:
      max-active: 8   # 连接池最大连接数（使用负值表示没有限制）
      max-wait: -1    # 连接池最大阻塞等待时间（使用负值表示没有限制）
      max-idle: 20    # 连接池中的最大空闲连接
      min-idle: 0     # 连接池中的最小空闲连接

#  zipkin:
#    enabled: true
#    baseUrl: http://eshop-zipkin-dashboard/
#  sleuth:
#    sampler:
#      #  默认值为0.1f，现在为了测试设置100%采集
#      percentage: 1

eureka:
  client:
    registerWithEureka: true #是否将自己注册到Eureka服务中，默认为true
    fetchRegistry: true #是否从Eureka中获取注册信息，默认为true
    serviceUrl: #Eureka客户端与Eureka服务端进行交互的地址
      defaultZone: ${eurekaServerUrl:http://root:root@127.0.0.1:8080/eureka/}
  instance:
      prefer-ip-address: true #将自己的ip地址注册到Eureka服务中
      ip-address: ${ipAddress:127.0.0.1}